export const USER_ROLES = {
  ADMIN: "ADMIN",
  ACCESS_OPERATOR: "ACCESS_OPERATOR",
  ACCESS_MONITOR: "ACCESS_MONITOR",
  SECURITY_MANAGER: "SECURITY_MANAGER",
  ACCESS_APPROVER: "ACCESS_APPROVER",
  ACCESS_REQUESTER: "ACCESS_REQUESTER",
} as const;

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES];

export const DOCUMENT_TYPES = {
  IDENTIFICATION: "IDENTIFICATION",
  TRAINING: "TRAINING",
  SPECIAL_PERMISSION: "SPECIAL_PERMISSION",
} as const;

export type DocumentType = (typeof DOCUMENT_TYPES)[keyof typeof DOCUMENT_TYPES];

export const DOCUMENT_RECORD_TYPES = {
  IDENTITY_CREDENTIAL: "IDENTITY_CREDENTIAL",
  TRAINING_EVIDENCE: "TRAINING_EVIDENCE",
  LEGAL_AUTHORIZATION: "LEGAL_AUTHORIZATION",
  ISSUER_CARD: "ISSUER_CARD",
  EMPLOYER_AUTHORIZATION: "EMPLOYER_AUTHORIZATION",
  SITE_INDUCTION: "SITE_INDUCTION",
  MEDICAL_SUITABILITY: "MEDICAL_SUITABILITY",
  WORK_PERMIT: "WORK_PERMIT",
} as const;

export type DocumentRecordType =
  (typeof DOCUMENT_RECORD_TYPES)[keyof typeof DOCUMENT_RECORD_TYPES];

export const DOCUMENT_EXPIRY_BASES = {
  LAW: "LAW",
  COLLECTIVE_AGREEMENT: "COLLECTIVE_AGREEMENT",
  ISSUER: "ISSUER",
  EMPLOYER_POLICY: "EMPLOYER_POLICY",
  CLIENT_POLICY: "CLIENT_POLICY",
  RISK_ASSESSMENT: "RISK_ASSESSMENT",
  LEGACY_UNKNOWN: "LEGACY_UNKNOWN",
  NOT_APPLICABLE: "NOT_APPLICABLE",
} as const;

export type DocumentExpiryBasis =
  (typeof DOCUMENT_EXPIRY_BASES)[keyof typeof DOCUMENT_EXPIRY_BASES];

export const DOCUMENT_STATUSES = {
  PENDING_REVIEW: "PENDING_REVIEW",
  VALIDATED: "VALIDATED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  ARCHIVED: "ARCHIVED",
} as const;

export type DocumentStatus =
  (typeof DOCUMENT_STATUSES)[keyof typeof DOCUMENT_STATUSES];

export const PLANNED_ACCESS_STATUSES = {
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELED: "CANCELED",
  EXPIRED: "EXPIRED",
  USED: "USED",
  PARTIALLY_USED: "PARTIALLY_USED",
} as const;

export type PlannedAccessStatus =
  (typeof PLANNED_ACCESS_STATUSES)[keyof typeof PLANNED_ACCESS_STATUSES];

export const WORK_PERMIT_STATUSES = {
  DRAFT: "DRAFT",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  REVOKED: "REVOKED",
  CLOSED: "CLOSED",
} as const;

export type WorkPermitStatus =
  (typeof WORK_PERMIT_STATUSES)[keyof typeof WORK_PERMIT_STATUSES];

export const ACCESS_DECISIONS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  DENIED: "DENIED",
} as const;

export type AccessDecision =
  (typeof ACCESS_DECISIONS)[keyof typeof ACCESS_DECISIONS];

export const WORK_DECISIONS = {
  NOT_REQUIRED: "NOT_REQUIRED",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  DENIED: "DENIED",
} as const;

export type WorkDecision =
  (typeof WORK_DECISIONS)[keyof typeof WORK_DECISIONS];
